version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/opt/data/minibrew/ftp/data:/home/minibrew/"
      - "/opt/data/minibrew/ftp:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: minibrew
      FTP_USER_PASS: pass1
      FTP_USER_HOME: /home/minibrew
    restart: always
